name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  run:
    - name: Run with setup-python 3.8.1
      uses: ./
      with:
        python-version: 3.8.1
    - run: python hello-world.py